<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515180317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adding draft data with picks and bans';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE draft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) DEFAULT \'creating\' NOT NULL, is_sandbox BOOLEAN DEFAULT false NOT NULL, identifier UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_467C9694772E836A ON draft (identifier)');
        $this->addSql('CREATE TABLE draft_ban (side VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE, draft_id INT NOT NULL, champion_id INT NOT NULL, PRIMARY KEY (draft_id, champion_id))');
        $this->addSql('CREATE INDEX IDX_F81CA9F1E2F3C5D1 ON draft_ban (draft_id)');
        $this->addSql('CREATE INDEX IDX_F81CA9F1FA7FD7EB ON draft_ban (champion_id)');
        $this->addSql('CREATE TABLE draft_pick (side VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE, draft_id INT NOT NULL, champion_id INT NOT NULL, PRIMARY KEY (draft_id, champion_id))');
        $this->addSql('CREATE INDEX IDX_838D399FE2F3C5D1 ON draft_pick (draft_id)');
        $this->addSql('CREATE INDEX IDX_838D399FFA7FD7EB ON draft_pick (champion_id)');
        $this->addSql('ALTER TABLE draft_ban ADD CONSTRAINT FK_F81CA9F1E2F3C5D1 FOREIGN KEY (draft_id) REFERENCES draft (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE draft_ban ADD CONSTRAINT FK_F81CA9F1FA7FD7EB FOREIGN KEY (champion_id) REFERENCES champion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE draft_pick ADD CONSTRAINT FK_838D399FE2F3C5D1 FOREIGN KEY (draft_id) REFERENCES draft (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE draft_pick ADD CONSTRAINT FK_838D399FFA7FD7EB FOREIGN KEY (champion_id) REFERENCES champion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE draft ADD blue_team_uuid UUID NOT NULL');
        $this->addSql('ALTER TABLE draft ADD red_team_uuid UUID NOT NULL');
        $this->addSql('ALTER TABLE draft ADD spectator_uuid UUID NOT NULL');
        $this->addSql('ALTER TABLE draft ADD max_timer INT DEFAULT 60 NOT NULL');
        $this->addSql('ALTER TABLE draft ADD blue_team_ready_checked BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE draft ADD red_team_ready_checked BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE draft ADD name VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE draft ADD blue_team_name VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE draft ADD red_team_name VARCHAR(32) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE draft_ban DROP CONSTRAINT FK_F81CA9F1E2F3C5D1');
        $this->addSql('ALTER TABLE draft_ban DROP CONSTRAINT FK_F81CA9F1FA7FD7EB');
        $this->addSql('ALTER TABLE draft_pick DROP CONSTRAINT FK_838D399FE2F3C5D1');
        $this->addSql('ALTER TABLE draft_pick DROP CONSTRAINT FK_838D399FFA7FD7EB');
        $this->addSql('DROP TABLE draft');
        $this->addSql('DROP TABLE draft_ban');
        $this->addSql('DROP TABLE draft_pick');
    }
}
