<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515143205 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adding champions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE champion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lol_id VARCHAR(16) NOT NULL, lol_key VARCHAR(3) NOT NULL, image_full VARCHAR(255) NOT NULL, image_sprite VARCHAR(255) NOT NULL, image_x INT NOT NULL, image_y INT NOT NULL, image_width INT NOT NULL, image_height INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE champion_data (language VARCHAR(5) NOT NULL, name VARCHAR(16) NOT NULL, title VARCHAR(255) NOT NULL, champion_id INT NOT NULL, PRIMARY KEY (champion_id, language))');
        $this->addSql('CREATE INDEX IDX_61A372DAFA7FD7EB ON champion_data (champion_id)');
        $this->addSql('ALTER TABLE champion_data ADD CONSTRAINT FK_61A372DAFA7FD7EB FOREIGN KEY (champion_id) REFERENCES champion (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE champion_data DROP CONSTRAINT FK_61A372DAFA7FD7EB');
        $this->addSql('DROP TABLE champion');
        $this->addSql('DROP TABLE champion_data');
    }
}
